### ISSUE TITLE
Mouse Pointer auto enable

### ISSUE THREAD

**Issue by vineshsn** [rsmoorthy/ishapi#1]
The default operation of Kodi enabling the mouse pointer after a certain time of disabling it by the user needs to remain disabled until manually it's enabled again

**Comment by rsmoorthy** [comment]
So far, there is no evidence of mouse pointer getting enabled by itself. Let us observe for more time and if it happens, let us explore (disable mouse movements) and implement

**Comment by vineshsn** [comment]
Checked now with the 3B model... It's getting enabled automatically.. If needed I'll send the video for understanding.

**Comment by vineshsn** [comment]
Needs to be reopened
