### ISSUE TITLE
Linux Pendrive for quick encryption from Laptop or PC

### ISSUE THREAD

**Issue by vineshsn** [rsmoorthy/ishapi#22]
Anna,
We'll need a Linux Pendrive for quick encryption from Laptop or PC unlike using the Raspberry Pi for encryption on the Micro SD card using WinSCP or AndFTP app...
Pranam

**Comment by vineshsn** [comment]
Virtualbox ISO image for laptop users and encryption which will give access for local Hard drive of the host machine to create encrypted volumes

**Comment by rsmoorthy** [comment]
Completed some time back

**Comment by vineshsn** [comment]
Illa... Adu velai seyyala.... Instead we shifted copying the files using
the terminal kind of app to copy the unencrypted files.

**Comment by rsmoorthy** [comment]
If it is not working, please follow up and get it fixed. It is WORKING for me. 
But I realise that you don't want to use this feature any more, after you found another way.
