### ISSUE TITLE
Audio of the 192 kbps video files have disturbance via composite output

### ISSUE THREAD

**Issue by vineshsn** [rsmoorthy/ishapi#26]
The sound of the 192 kbps video files have disturbance via composite output. This is for the record sake where we can also note down the solution that was arrived.

**Comment by rsmoorthy** [comment]
Setting
audio_pwm_mode=1
in /boot/config.txt  seems to solve the problem

**Comment by vineshsn** [comment]
Observation : By doing the above operation, under System settings->Audio Output->ALSA:xxxxxxxx was gone. This happened when I removed all the unnecessary lines except the ones that we know and use
