### ISSUE TITLE
Mobile Number 2 & 3 optional

### ISSUE THREAD

**Issue by vineshsn** [rsmoorthy/ishapi#27]
During user registration it'll be better to have another 2 more mobile numbers for user to enter in case of network failure in any particular sim card the top could be sent to other optional numbers

**Comment by rsmoorthy** [comment]
Mobile number 2 is allowed to be added optionally. This number will not be used for any authentication. This is only for information purpose.

I have installed several apps, never found people authenticating with *two* mobile numbers.
