### ISSUE TITLE
Screensaver calling key in the fly air mouse not working

### ISSUE THREAD

**Issue by vineshsn** [rsmoorthy/ishapi#33]
Search button on the left side of the play/pause button. I don't know if this was created or only the screensaver calling script was written.

**Comment by rsmoorthy** [comment]
This is working still fine for me. As we saw the other day, your mouse is a different variant than mine. You did a debug exercise and found that the search key is mapped to f3. Setting the key mapping to f3 also did not solve.

I think we need to do the exercise again, with your air mouse and then fix it. I am assigning this to you, whenever you are ready - we can do this again.

**Comment by vineshsn** [comment]
It's working Anna
