### ISSUE TITLE
Music folder in Rootfs to be given permission

### ISSUE THREAD

**Issue by vineshsn** [rsmoorthy/ishapi#36]
The Music folder in Rootfs to be given permission to add files and play music files as the volunteers would not be able to play it until the teacher brings their mobile to authenticate and Mount the volume.

**Comment by rsmoorthy** [comment]
Can you create one or more directories under /mnt/Ishamedia and place unencrypted files directly under that? This way, users can just go to "Ishamedia" folder and see all their files there. Unencrypted files will always be visible, whether teacher connects to it or not.

If the above solution is okay, please close the ticket yourself.

**Comment by vineshsn** [comment]
This is also fine Anna 🙏
Pranam

**Comment by vineshsn** [comment]
Hey,

I just signed the petition ". @narendramodi @PMOIndia @imrankhanPTI @United
Nations: Release of Indian Wing Commander Abhinandan with honour from
Pakistan" and wanted to see if you could help by adding your name.

Our goal is to reach 25,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/qRsHChSXSd

Thanks!
Vinesh
