### ISSUE TITLE
List of volumes mounted 

### ISSUE THREAD

**Issue by vineshsn** [rsmoorthy/ishapi#41]
In the home page of iPi app on clicking the connect it would be good to display the encrypted volume getting mounted one after another for the user to know.

**Comment by rsmoorthy** [comment]
Fixed it with App 1.0.10 and Pi patch version 2019040401. 

The volumes mounted will show only after the Connect is clicked. If a USB pendrive is inserted and the volumes are mounted on Pi, the App won't show the latest volumes. If you want to get the latest volumes, then just press Connect.
