### ISSUE TITLE
Music files under \storage\ishamedia folder not listed in the app 

### ISSUE THREAD

**Issue by vineshsn** [rsmoorthy/ishapi#44]
The Music files stored under \storage\ishamedia folder after encryption process are not listed in the app under music section as it displays the encrypted video files under video section

**Comment by rsmoorthy** [comment]
May be it is not mounted? I am not very clear on the problem. I will try this anyway now.

**Comment by vineshsn** [comment]
It is mounted and viewable on the screen Anna..

Pranam

**Comment by rsmoorthy** [comment]
oh, you are saying -- it is not visible in the "Remote Pi" in the app, is it?

**Comment by vineshsn** [comment]
Yes

**Comment by rsmoorthy** [comment]
Fixed it in 1.0.10 app update
