### ISSUE TITLE
Connect button issue

### ISSUE THREAD

**Issue by vineshsn** [rsmoorthy/ishapi#46]
On the home screen below the IP address the connect button is referring with 'Host not reachable' or 'Network Error' messages while the Pi is still mounting the encrypted volumes. So after establishing the app and Pi connectivity of it can wait till all the volumes are mounted it'll not be misleading to the user.

**Comment by rsmoorthy** [comment]
This is fixed in 1.0.14. We first check if we can connect to Pi (with a small timeout). Then, we try to mount the volumes (with a much larger timeout).
