### ISSUE TITLE
Filter, Search and Region information under users section for Admin

### ISSUE THREAD

**Issue by vineshsn** [rsmoorthy/ishapi#47]
If Search option is made available under users section it'll be helpful to check out update any users credentials. Filter could be used to see users of specific roles or group or region.

The 'Region' management of users will be given under admin action or admin tasks section where if a new region needs to be created it'll be given here (For Ex. AP&T, Western, Eastern, North, South or TN, etc.,). But assigning a pre-created region to every user will be done under users section.

**Comment by rsmoorthy** [comment]
Please provide me the list of Regions

**Comment by vineshsn** [comment]
North
South
East
West
AP & Telangana
TN-North
TN-South
TN-East
TN-West
Chennai
APAC
UK
US
Middle East
China
Europe

Pranam

**Comment by rsmoorthy** [comment]
This is fixed in 1.0.15

**Comment by rsmoorthy** [comment]
You can filter in one of the following ways:
a) Simple Filter: Just type few chars of either name / mobile / email. Like just typing 'moo' will list all names or emails or mobile having those characters.

b) Advanced Filter: See examples for illustration
"disabled:Yes"    for all disabled users
"group:group1" for a list of all users in "Group1"
"region:US" for a list of all users in US region
"role:admin" for a list of admin roles (this will return "UserAdmin" roles also)

"group:group2 disabled:Yes"   for all disabled users in Group2
"region:chennai group:group1 mobile:98"  for all users in  region chennai, who are in group1 with mobile number  having 98 in them.

As of now, no negative searches or complex combination of "and" / "or" is possible.

The fields available are: name,mobile,email,region,group,disabled,role

**Comment by vineshsn** [comment]
Could you add Ashram as one more region? Is it possible for me to create region in the current version?
