### ISSUE TITLE
Add helptext - Rule to assign the size of the encryption volume

### ISSUE THREAD

**Issue by vineshsn** [rsmoorthy/ishapi#53]
If the Rule to assign the size of the encryption volume can be updated under the description of size it'll be helpful to give the size accordingly (i.e., for file size in MB it should be xxxM and for filesize in GB it should be xxG)

**Comment by rsmoorthy** [comment]
This helptext is already there, isn't it? It says "ex: 100M"

**Comment by rsmoorthy** [comment]
Anyway, helptext added in 1.0.14
