### ISSUE TITLE
Creation of playlist with both Video and Audio files is possible in Kodi

### ISSUE THREAD

**Issue by vineshsn** [rsmoorthy/ishapi#56]
I've checked that Kodi is supporting the playing of Video and audio files in one playlist. The steps are
1. The playlist is viewable only in video menu
2. Right click the list of files you want in playlist in the order that you want to be played and select 'Queue item'
3. After doing the above steps, go to video menu and open the left side menu and select 'Go to playlist or queue'
4. One will see the list of video and audio files in the order it was added to the queue. Once again the left menu select 'save' playlist. Give the name for the playlist.
5. This will create an xxx.m3u file

**Comment by rsmoorthy** [comment]
Better handled in IMC. Wont do it in Kodi.
