### ISSUE TITLE
Add-ons can get added

### ISSUE THREAD

**Issue by vineshsn** [rsmoorthy/ishapi#64]
This issue was brought up by Tr.Thomas. He said that it can get added they .zip file or something from settings. He says he'll keep you posted. I don't know..🙏

**Comment by ThomasKinder11** [comment]
It is still possible to install plugins by selecting 

"System-> Addons -> Running ->... "

There we have the option to install pluginsfrom zip file.  I installed a plugin this way from USB memory drive.

**Comment by rsmoorthy** [comment]
Thanks Thomas. This is getting fixed in the next patch (rescheduled to Tuesday)
