### ISSUE TITLE
User Disable function

### ISSUE THREAD

**Issue by vineshsn** [rsmoorthy/ishapi#77]
Currently the 'reload button' or the 'refresh' button on the top right corner of the home screen only is checking the server for credential update. Henceforth
1. Every user's app will check with our server every 14 days for the credentials update
2. The 'Connect' button will check with server every 7th time.(But while doing this mobile data will be usually disconnected and stay connected on WiFi of the Pi)
3. Also as a reminder everytime the app is opened it needs to check for the credentials from the server.

**Comment by rsmoorthy** [comment]
Fixed in 1.0.17

Except point 2, which I am not going to implement. On second thoughts, I think this is not needed.
