### ISSUE TITLE
v2.0.2-1 Mouse pointer is visible and should be hidden

### ISSUE THREAD

**Issue by ThomasKinder11** [rsmoorthy/ishapi#82]
Right now the mouse pointer is visible but we never use the mouse. We could disable this by adding 

-nocursor

Option to xinit command called in /etc/systemd/system/imc.service

**Comment by rsmoorthy** [comment]
Thanks again for identifying the solution as well. Makes my life much easy!

**Comment by rsmoorthy** [comment]
Fixed in some 2.0.x version
