### ISSUE TITLE
v2.0.2-1 Power button not working

### ISSUE THREAD

**Issue by ThomasKinder11** [rsmoorthy/ishapi#83]
Right now the power button of the remote control shuts down the system immediately as systemd is configured to handle power key presses. We need to disable power button handling by systemd which could be done by uncomment the line that says **#HandlePowerKey=poweroff** and change the value to **ignore** in **/etc/systemd/logind.conf**

**Comment by rsmoorthy** [comment]
Thanks Thomas for identifying the fix as well. Will fix it in the next release.

**Comment by rsmoorthy** [comment]
Fixed in the subsequent release.
