### ISSUE TITLE
v2.0.2-1 Usb symbolic links are not deleted after unplugging the USB drive

### ISSUE THREAD

**Issue by ThomasKinder11** [rsmoorthy/ishapi#84]
When I unplug the USB drive the symbolic links under /mnt/Ishamedia are not detected. This means that I do not get a file system update and therefore the directory view is not updated. 

Is it possible to delete the symbolic links to USB drivers if the usb memory device is unplugged?

**Comment by rsmoorthy** [comment]
Thomas, It was working. I just now realised that there was a copy paste problem and it has not been working due to that.

Please edit /etc/usbmount/umount.d/02_unmount and add a "#" at the beginning of the first line. (It should be "#!/bin/bash"). I will fix this in the next release.

**Comment by rsmoorthy** [comment]
Fixed in the subsequent release
