### ISSUE TITLE
Add credential screen before home screen

### ISSUE THREAD

**Issue by vineshsn** [rsmoorthy/ishapi#9]
During the first time login only

**Comment by vineshsn** [comment]
Also, it would be good to add the status of the 'Disabled : Yes or No' in the home screen of the users to know who are active and deactivated detail..

**Comment by vineshsn** [comment]
Surry closed it by mistake

**Comment by rsmoorthy** [comment]
This is fixed in 1.0.14.

Also, Disabled status is provided in the User listing, if it is Disabled.
